
[file."blend/fishes.blend"]
"fish-00" = { object = "Fish.001", z_frames = 8, width = 64, optical_size = 5.3 }
"fish-01" = { object = "Fish.002", z_frames = 8, width = 64, optical_size = 5.2 }
"fish-02" = { object = "Fish.003", z_frames = 8, width = 64, optical_size = 5.3 }
"fish-03" = { object = "Fish.004", z_frames = 8, width = 64, optical_size = 5.5 }
"fish-04" = { object = "Fish.005", z_frames = 8, width = 64, optical_size = 2.3 }
"fish-05" = { object = "Fish.006", z_frames = 8, width = 64, optical_size = 3.0 }
"fish-06" = { object = "Fish.007", z_frames = 8, width = 64, optical_size = 3.7 }
"fish-07" = { object = "Fish.008", z_frames = 8, width = 64, optical_size = 2.8 }

[file."blend/fishes2.blend"]
"grass-00" = { object = "grass", z_frames = 8, width = 64, optical_size = 2.3 }
"shoe" = { object = "shoe", z_frames = 8, width = 64, optical_size = 1.7 }
"starfish-00" = { object = "starfish-0", z_frames = 8, width = 64, optical_size = 2.1 }
"starfish-01" = { object = "starfish-1", z_frames = 8, width = 64, optical_size = 1.9 }
"starfish-02" = { object = "starfish-2", z_frames = 8, width = 64, optical_size = 1.9 }
"starfish-03" = { object = "starfish-3", z_frames = 8, width = 64, optical_size = 1.9 }
"starfish-04" = { object = "starfish-4", z_frames = 8, width = 64, optical_size = 1.9 }

[file."blend/ships.blend"]
"ship-00" = { object = "ships", z_frames = 16, x_frames = 5, width = 64, optical_size = 1.4 }
"ship-01" = { object = "ships.001", z_frames = 16, x_frames = 5, width = 64, optical_size = 2.1 }
"sail-00-0" = { object = "sail-00-0", z_local_frames = 16, z_frames = 16, x_frames = 5, width = 64, optical_size = 1.4 }
"sail-00-1" = { object = "sail-00-1", z_local_frames = 16, z_frames = 16, x_frames = 5, width = 64, optical_size = 1.4 }
"sail-00-2" = { object = "sail-00-2", z_local_frames = 16, z_frames = 16, x_frames = 5, width = 64, optical_size = 1.4 }
"sail-00-3" = { object = "sail-00-3", z_local_frames = 16, z_frames = 16, x_frames = 5, width = 64, optical_size = 1.4 }
"sail-00-4" = { object = "sail-00-4", z_local_frames = 16, z_frames = 16, x_frames = 5, width = 64, optical_size = 1.4 }

[file."blend/harbour.blend"]
"harbour-00" = { object = "harbour", z_frames = 6, width = 512, optical_size = 3.5 }

[sail."basic"]
mast_offset = 1.3
area = 1.0
reefing_stages = [ "sail-00-0", "sail-00-1", "sail-00-2", "sail-00-3", "sail-00-4" ]
